# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT051 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.1/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.1.tar.xz"
      sha256 "6e307f7d30c58c0a6d86a5843c3c9c24f13119974bdf502bca16d0242ae8c299"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.1/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.1.tar.xz"
      sha256 "30d511c7359b68f0092a89631afcafe493e54062af8552736fcc4afb05c86848"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.1/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.1.tar.xz"
      sha256 "4b0e229e367310498282157e26e93c06a7031234745090061f3f706b361528ee"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
