# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT060 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.0/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.6.0.tar.xz"
      sha256 "7c7febc99c7d83cec9d44e19e1628ca68505ee785038a024b2af1e84b2c2228f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.0/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.6.0.tar.xz"
      sha256 "64f1741dae03dc11091bd1d7e0ac148d98108db6fe0782fa06f99b099d434241"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.0/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.6.0.tar.xz"
      sha256 "9d27214d8cc6b807a28387fb22de87c02cc6c582a9a63ffa869e62373c249678"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
