# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT04 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.3/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.4.3.tar.xz"
      sha256 "780b973a4942949418beab21c308116af89bad3346a01f0d6a72d4817114b02e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.3/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.3.tar.xz"
      sha256 "28f09074c30aa965bd4d01fcc6ba73d3d0cda9fc65a1937fae830fdee4617d92"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.3/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.3.tar.xz"
      sha256 "a9fc892756e79240491946cd88566f232674df6e838b019a380e39ee0298fe45"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
