# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT072 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.2/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.7.2.tar.xz"
      sha256 "78577702bf93e8a5e6971cf380898476f6b34ffe056135d8d30857c5836718f7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.2/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.2.tar.xz"
      sha256 "7e607b8b2255f1fbcf18f74741a0e53e97b2d34cf9fe2c8affab542861e86d48"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.2/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.2.tar.xz"
      sha256 "49f5540071c887c438924b9412843b31961bdf7cd1ce7e116ec0842e16e6ace5"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
