# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT073 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.3/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.7.3.tar.xz"
      sha256 "c0743d8912e4433abeade0f08d9c4e48c66cd9fd680c9e5704546dfd10caff38"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.3/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.3.tar.xz"
      sha256 "a6792c850e9298131d2f5a526cb1d6520eb6abe04edf355c1c5c709dcb1f871b"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.3/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.3.tar.xz"
      sha256 "8066802f78344ccbb459c815a48071c29f3c5abb70cd18d1867c54a71ea1f01d"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
