# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT070 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.0/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.7.0.tar.xz"
      sha256 "e56a7e0a8d72c83c4af50daf5c787e879ce142b86284d71d749ce8072b502c4a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.0/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.0.tar.xz"
      sha256 "5346cfc1d81ac9d9fb7546618c56297d99deb539e1903a46133e25fbb79104ad"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.0/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.0.tar.xz"
      sha256 "1c214ec9232b6c7d54a4dcf68acbf25701fc2c6bdafd662f9b774c5a3268c379"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
