# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT05 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.10/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.10.tar.xz"
      sha256 "efdfb2af766d59581b7e1b76832c2734226c2f1bbbff2a973fb8cdbe88254bb7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.10/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.10.tar.xz"
      sha256 "8ce4bcd79f7b197193c210a8793e329ef3207baac263e804a86c50fa7dc81bcb"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.10/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.10.tar.xz"
      sha256 "d59aab6b8022ca42eb11327ce7ab40274441eb782ed2729c069a99a5df7d7118"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
