# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT059 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.9/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.9.tar.xz"
      sha256 "45fcf02aa6a2545078757047be9771f55521a7cf33eecafec8633294c418ad1e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.9/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.9.tar.xz"
      sha256 "b62b61dfb0cb77c0a1a3caa88fe356b56a815728b7e2e7afa1c4e8efc807ddce"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.9/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.9.tar.xz"
      sha256 "0901b27c73f221859ef3ee4d122c940cdb80dffad8dc1ed45b578876ab01059b"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
