# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT057 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.7/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.7.tar.xz"
      sha256 "1e2f39865f7a46f356ae352a0c56a236f5afe072f20711efec7a3e77fec22571"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.7/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.7.tar.xz"
      sha256 "a3704a47934048bfc34108dfba5274c9abdd723d3b88338c878ef34033da14ba"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.7/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.7.tar.xz"
      sha256 "74bdd23fd416efb28a797ab2102aadd4d14d7430dc7d7ab818a6c594262b1218"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
