# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT040 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.0/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.4.0.tar.xz"
      sha256 "a00b2f2ac99dcbd26184f6e6bbaea67081cd2b22d1c883de28ccfff4558507c2"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.0/spellcaster-x86_64-apple-darwin.tar.xz#/spellcaster-0.4.0.tar.xz"
      sha256 "d88da15a1e5f6ca5887c49615f6661f543d48af1896f06f5b99020cfb998405d"
    end
  end

  on_linux do
    depends_on arch: :x86_64
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.0/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.0.tar.xz"
      sha256 "edeeb1190371e2ccda0265b29b2d976f8186a65910946ae4862521c2f6fe2de1"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
