# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT06 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.2/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.6.2.tar.xz"
      sha256 "b362915d89b69ae81c72ea9a080eac1c55db7e736e8666a3802e303e1fc607fe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.2/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.6.2.tar.xz"
      sha256 "87a29a847469169c38ee30e1ebf5ba79a3688d0e5a8eb8b70cc1fb6fd3825762"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.2/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.6.2.tar.xz"
      sha256 "d21908790eee5a3f5d8a8964fc87faf7258f124d832bf79dfdc1246348b2ab80"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
