# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT031 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.3.1/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.3.1.tar.xz"
      sha256 "228d099cdb91d68459c250e6065aa005e5265d3fa1a50233c0ba62c760fa3cf8"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.3.1/spellcaster-x86_64-apple-darwin.tar.xz#/spellcaster-0.3.1.tar.xz"
      sha256 "eb5f515c2272690bc1d9164d62815b39c5c6c22969bbf04bb2f342d21cd47497"
    end
  end

  on_linux do
    depends_on arch: :x86_64
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.3.1/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.3.1.tar.xz"
      sha256 "1e6cf6a7fa16e24f8c38043eee3f4cdb77552722a75d2a7a58bdf32cd334e194"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
