# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT042 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.2/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.4.2.tar.xz"
      sha256 "3c63bc64a72853c49ced80957dd734fa32a5e3536d2d73a4bcfc1deeaeda5767"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.2/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.2.tar.xz"
      sha256 "0d32a2328d5fa7213d1c195535206bcb2a7800fbd525074005cfb803f3cca53f"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.2/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.2.tar.xz"
      sha256 "43e5a63a76e97db1cc23c3aeee5557bb5ad40b0ad9e7b2d2ff34a9f9a6d41f0d"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
