# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT071 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.1/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.7.1.tar.xz"
      sha256 "f2148af29f93a7091f1f382f41933fd621af5b9098cf632e418a9d937a7cefd1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.1/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.1.tar.xz"
      sha256 "ce27ce9e16a5836f942993cce716e2301b709b7128829fd702cfc73b4873c5d2"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.1/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.1.tar.xz"
      sha256 "95caccbff0746af15609a17dae97fcbb8ef84b1235ce0e7f074a409db6df9187"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
