# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT075 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.5/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.7.5.tar.xz"
      sha256 "43b03a3473eca3ae41eb570b133e1aca2d4a0af5e040afebc442d045e011e09c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.5/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.5.tar.xz"
      sha256 "f8ab4813805a45040df1ebe32bf6e6e7bbe35967232f7f954a2dfcc70304e88a"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.5/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.5.tar.xz"
      sha256 "186a47ca4efdc4e27b282061b969628363be6d2e9309fd0fc6bba1fca22c799c"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
