# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT052 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.2/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.2.tar.xz"
      sha256 "8f8031a5b6bb6917a1a436b3b523b84808f9c024c1ac646931920ed8dcbd9f15"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.2/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.2.tar.xz"
      sha256 "710361dbc201aeaba4afcbbe6e1541920afcfb0220da6fd2c5dc8850589d6228"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.2/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.2.tar.xz"
      sha256 "5ada7ff23a3e24e958b6a9735b16f2c7cf2c2ca94e4884a93562df23fe800778"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
