# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT054 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.4/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.4.tar.xz"
      sha256 "deb4b33cf9dca20de8393d6d4abf31d8c0b89dff6c7b7976902f92be5e4f493a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.4/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.4.tar.xz"
      sha256 "a9f9c101944f587327763f7ea97cff387d6818267d211ac7c4815d9b0097c87b"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.4/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.4.tar.xz"
      sha256 "54b251ee0237a19bdb025c2d7e0f9671abd804e604d510ff9ee5ea31dd418d68"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
