# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT050 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.0/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.0.tar.xz"
      sha256 "9fcc720628e4003ff1a5423841fa38a5296b77e682bfb5a6181c596da52666b4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.0/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.0.tar.xz"
      sha256 "71c5e8aa42fa52efc7837780776dd146178a338c3dc9a4997bb8a119666b7825"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.0/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.0.tar.xz"
      sha256 "6b658a06ee0d2551dbb90471cf082560da4282f728b9cb5ebbada4edbdd78381"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
