# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT053 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.3/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.3.tar.xz"
      sha256 "6e4cf7e7d05f19c9ffd649ccdae18f6db71e03ea66109b16f5a1035b095ffea1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.3/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.3.tar.xz"
      sha256 "a47e22a4390526d91ccc11a70820ca83288c51061e45122bbfd2dcb2fdb45c6e"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.3/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.3.tar.xz"
      sha256 "095c9e4875bbd8f89f9c2bd538f568036c16ed0ceb2e7c6dc8b44814d00bd441"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
