# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT041 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.1/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.4.1.tar.xz"
      sha256 "cfe1ff88a096595a07b0c5276c38e1bc9a841faa48f5c0f6e9eeb2e0fbcc1f82"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.1/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.1.tar.xz"
      sha256 "4b2cec5f3f7b9d621301aa432a78be59b0979bc485a420f1ce00bf445bce0e14"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.4.1/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.4.1.tar.xz"
      sha256 "1f372c2a301ca2d8a73ad7b6e788b5273edbcb2195bd1a54ef74e137ba192669"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
