# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT061 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.1/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.6.1.tar.xz"
      sha256 "dbab821bac6a9c0fb0c7772397cd1165179a4a168189e686d5cdb5fb01be2d7a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.1/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.6.1.tar.xz"
      sha256 "ca92da73cc334cf91a8705c27e5111a9a8edb35f8359b84be48105fd0308258e"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.6.1/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.6.1.tar.xz"
      sha256 "19564448967c12aba1624217a65082fa3ad45caa98bf48c208e6323807b95281"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
