# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT074 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.4/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.7.4.tar.xz"
      sha256 "55f13f768756e8b66b68f689b7a378afdbceafd27b91fe6c389e66651bb765d9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.4/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.4.tar.xz"
      sha256 "44e0b4578d31a1a1aeea7009b4c90863925249db6036c17ca01a0a274c6b0539"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.7.4/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.7.4.tar.xz"
      sha256 "f7e817789a60f866c20aeebe10eca7b66e552a2a7c99e8903d3426cacda6d08b"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
