# Generated by scripts/sync_formulae.py -- do not edit by hand.
class SpellcasterAT056 < Formula
  desc "Makina operator CLI"
  homepage "https://makina.finance"
  license :cannot_represent

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.6/spellcaster-aarch64-apple-darwin.tar.xz#/spellcaster-0.5.6.tar.xz"
      sha256 "3b4e61c3f9dd672bf47c1ba7c56ba85b027a17a7992891b33fe52cc3995f32af"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.6/spellcaster-aarch64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.6.tar.xz"
      sha256 "96b4986bda2a27d624319d6ec3535515fa149580d445ecdd04886bd0a7715990"
    end
    on_intel do
      url "https://github.com/MakinaHQ/spellcaster-releases/releases/download/spellcaster-v0.5.6/spellcaster-x86_64-unknown-linux-gnu.tar.xz#/spellcaster-0.5.6.tar.xz"
      sha256 "c255795627abc500497491f58fcec86929685f445cb8f68bf4eee99dbc11fdab"
    end
  end

  def install
    bin.install "spellcaster"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spellcaster --version")
  end
end
