# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT024 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.4/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.2.4.tar.xz"
      sha256 "70b9e88448b1f4600d303d94cb8c3703d747b2cb04576cc1569b3ae17f69d85a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.4/transpiler-aarch64-unknown-linux-gnu.tar.xz#/transpiler-0.2.4.tar.xz"
      sha256 "fcfd36654a586be3b4297c1da6fb5360842f26be78f7c95fd9c5fa8b10edf006"
    end
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.4/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.2.4.tar.xz"
      sha256 "9b42296ed74ec9a0830bd0e1f1724e730de30405ba7fae8f96b505bde2a76054"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
