# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT027 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.7/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.2.7.tar.xz"
      sha256 "afbf1331c48b4e0a2ca4683535718cc0e1b33ff4cfc5fc3c178ef36411de2620"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.7/transpiler-aarch64-unknown-linux-gnu.tar.xz#/transpiler-0.2.7.tar.xz"
      sha256 "894a30dc64f95b6f9ac172f80d9cbb34f988ba632bcaa3ec178cd7691011e695"
    end
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.7/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.2.7.tar.xz"
      sha256 "9b6fb125510147875762031c236b0307655341e6a579c5ff6621f2ddd9af749e"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
