# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT021 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.1/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.2.1.tar.xz"
      sha256 "3ea3d9cdab01a39b1ecceb0af318ea6f69998b0cddd59236d6abc5747c2056f1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.1/transpiler-aarch64-unknown-linux-gnu.tar.xz#/transpiler-0.2.1.tar.xz"
      sha256 "09a68bf4c5f4771e460faff01b5722b326286d4767dacf054c635e6caf24634d"
    end
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.1/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.2.1.tar.xz"
      sha256 "61cdfb12aece3afc95bfa2930caf1edc83999331ee95316a433dc3a7d5f1b441"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
