# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT023 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.3/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.2.3.tar.xz"
      sha256 "e5ad71701ec6289e66883e62cc4f0190fc172230854e1029e5b347ff4db32b53"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.3/transpiler-aarch64-unknown-linux-gnu.tar.xz#/transpiler-0.2.3.tar.xz"
      sha256 "4ffe6a4ca5d5e56ef6293a0c13a5ed04f608960e50b0c560a6a98da44f6f27af"
    end
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.3/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.2.3.tar.xz"
      sha256 "8aa663351bb1a9a63a52040cfbfb948f3ecbbea5af12bb05053dcdd13e4c66eb"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
