# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT020 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.0/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.2.0.tar.xz"
      sha256 "6c38d97316fbd9bb2915dcb04b281d18a237abc3b663308ad54945847522889e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.0/transpiler-aarch64-unknown-linux-gnu.tar.xz#/transpiler-0.2.0.tar.xz"
      sha256 "34aed3a6cd3c615eaa41cc48d6b297b4d2c8c9f504507e817cd703d3d9264727"
    end
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.0/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.2.0.tar.xz"
      sha256 "5245da140ea63933aa1663c611290864f70e70e90438c70cf5c0ba32330e116a"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
