# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT022 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.2/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.2.2.tar.xz"
      sha256 "bb9fb9c27f436697b8a4a76d796f910f89047d07a98929af62276fd8339fc35f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.2/transpiler-aarch64-unknown-linux-gnu.tar.xz#/transpiler-0.2.2.tar.xz"
      sha256 "446c12afc865fef37f5695fcbb14ac9b139ce84a0aa994660ec8a9889beb6e95"
    end
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.2.2/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.2.2.tar.xz"
      sha256 "49c6d4f13f69c06b9c2f5fa1a64f1b159052a6899e84dd851a0de42f69d7928d"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
