# Generated by scripts/sync_formulae.py -- do not edit by hand.
class TranspilerAT01 < Formula
  desc "Transpiles Makina instructions into executable weiroll scripts"
  homepage "https://github.com/MakinaHQ/transpiler"
  license "BUSL-1.1"

  keg_only :versioned_formula

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.1.0/transpiler-aarch64-apple-darwin.tar.xz#/transpiler-0.1.0.tar.xz"
      sha256 "a3d7fca1739e444c55c794fcd446f3886b56f5c9f21fae0ff9ef43665279b6d5"
    end
  end

  on_linux do
    depends_on arch: :x86_64
    on_intel do
      url "https://github.com/MakinaHQ/transpiler/releases/download/v0.1.0/transpiler-x86_64-unknown-linux-gnu.tar.xz#/transpiler-0.1.0.tar.xz"
      sha256 "2df1dce5cdd8c337cf8004b00c3d487ef8900693ec6c4bfd38320a49024eba7e"
    end
  end

  def install
    bin.install "transpiler"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/transpiler --version")
  end
end
